package shop;

public class Product {
	private String name; // Private means they are hidden away from things outside of the class
	private double price;

// constructor is automatically generated by right click inside the brackets clicking Source => Generate Constructor using Fields
// The code below we can see it is taking in a name and price and storing them inside our object

	public Product(String name, double price) {
		this.name = name; // this. means it belongs to the object
		this.price = price;
	}

// Here we generate getters by right click source => Generate getters and setters =>  Select name and price getters

	// This allows us to access the name
	public String getName() {
		return name;
	}

	// This allows us to access the price
	public double getPrice() {
		return price;
	}

// 2 string method is added to help with debugging
// Again can be automatically genetated by right clicking on Source => Generate a 2 string Method => Normally we will only want to print out the fields but others can be added if necessary

	@Override
	public String toString() {
		return "Product [name=" + name + ", price=" + price + "]";
	}
}

//C - char* (pointer) which represents more than one character stored in memory.
//Java has a shortcut for this which hides the complexity and is c
//Java is similar when it comes to numbers
//Structs only store data they don't have methods
